# Generated by Django 4.1.3 on 2022-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=10)),
                ("text", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("etc", models.JSONField()),
            ],
            options={
                "db_table": "blogs",
            },
        ),
    ]
